version: "3.7"
services:

  go-mqtt-to-influx:
    build:
      context: .
      dockerfile: docker/Dockerfile    
    ports:
      - "8880:8880"
    restart: unless-stopped    
    volumes:
      - ./config.yml:/app/config.yml
